## inital setting
data_source:

  raw_file: "E:\\01_Programming\\Py\\Aditya_MLPROCESS\\data\\00_raw\\credit_risk_dataset.csv"
  
  column_names    : ""
  
  drop_columns    : ""
  
  target_name     : ""
  
  test_size       : ""
  
  random_state    : ""



