## inital setting
data_source:

  raw_file        : "E:/01_Programming/Py/Aditya_MLPROCESS/data/00_raw/credit_risk_dataset.csv"

  target_col      : "loan_status"
  
  drop_columns    : ""
  
  test_size       : 0.2
  
  random_state    : 42

  num_cols        : ["person_age", "person_income", "person_emp_length", "loan_amnt",
                     "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length"]

  corr_cols       : ["person_age", "person_income", "peron_emp_length", "loan_amnt",
                     "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length", "loan_status"]

  cat_cols        : ["person_home_ownership", "loan_intent", "loan_grade", "cb_person_default_on_file"]

pickle_path:

  X_train         : "E:/01_Programming/Py/Aditya_MLPROCESS/data/01_interim/X_train.pkl"

  X_test         : "E:/01_Programming/Py/Aditya_MLPROCESS/data/01_interim/X_test.pkl"

  X_valid         : "E:/01_Programming/Py/Aditya_MLPROCESS/data/01_interim/X_valid.pkl"

  y_train         : "E:/01_Programming/Py/Aditya_MLPROCESS/data/01_interim/y_train.pkl"

  y_test         : "E:/01_Programming/Py/Aditya_MLPROCESS/data/01_interim/y_test.pkl"

  y_valid         : "E:/01_Programming/Py/Aditya_MLPROCESS/data/01_interim/y_valid.pkl"

encoding_path:

  home_owner      : "E:/01_Programming/Py/Aditya_MLPROCESS/models/ohe_home_ownership.pkl"

  loan_intent     : "E:/01_Programming/Py/Aditya_MLPROCESS/models/ohe_loan_intent.pkl"

  loan_grade      : "E:/01_Programming/Py/Aditya_MLPROCESS/models/ohe_loan_grade.pkl"

  record_default  : "E:/01_Programming/Py/Aditya_MLPROCESS/models/ohe_default_on_file.pkl"

processed_files:

  X_train: "E:/01_Programming/Py/Aditya_MLPROCESS/data/02_processed/X_train_prep.pkl"

  X_test: "E:/01_Programming/Py/Aditya_MLPROCESS/data/02_processed/X_test_prep.pkl"

  X_valid: "E:/01_Programming/Py/Aditya_MLPROCESS/data/02_processed/X_valid_prep.pkl"

  y_train: "E:/01_Programming/Py/Aditya_MLPROCESS/data/02_processed/y_train_prep.pkl"

  y_test: "E:/01_Programming/Py/Aditya_MLPROCESS/data/02_processed/y_test_prep.pkl"

  y_valid: "E:/01_Programming/Py/Aditya_MLPROCESS/data/02_processed/y_valid_prep.pkl"






